### ISSUE TITLE
Subtask #195: Delivery Width Rule Creation

### ISSUE THREAD

**Issue by arne-z** [SiLeBAT/fcl-client#932]
Reference #195 

Tasks:

- [ ] add instructions for users how they need to provide the data to be used for this feature (as number formats, no units, same units) in standard font and standard font size in FCL
"Delivery Width can only be used for variables defined as numbers that do not contain the unit. Numbers must be on the same unit level (e.g. all in kg OR all in tons). If deliveries are merged in FCL Web, the highest single value of the contained deliveries is used."
- [ ] a big "+" button is shown
- [ ] add tool tip to the "+" button ("Add Delivery Width Rule)
![Image](https://github.com/user-attachments/assets/08cd3958-fa99-4b28-bc7b-560f2b9bf2fd)

Clicking on the "+"button triggers opening the settings dialogue below the "+" button:
- [ ] "+" button greyed out + inactive while the UI for creating a rule is open
- [ ] add free text field to enter a name for the rule
- [ ] add dropdown menu for "property" (see filter conditions) -->as a first step only show variables defined as number (e.g. score)
- [ ] add checkbox for "value type" with the entries "value" and "log value"
- [ ] add checkbox "Zero as minimum"
- [ ] add dropdown menu for "Max" (empty, 2, 3, 5, 10, 20) with the values indicated in brackets as in FCL Desktop
- [ ] There should be three buttons: Apply (leaves the dialogue as is and applies the settings to the graph), Cancel (deletes the values and closes the settings dialogue), OK (applies the settings to the graph and closed the settings dialogue and and adds the rule to a list)
- [ ] Apply and OK buttons only become active when name, property and value type are filled.
![Image](https://github.com/user-attachments/assets/4398266e-20c7-4686-8a7d-8fee5153c481)
