### ISSUE TITLE
Subtask #195: Handle editing and toggling of created rules.

### ISSUE THREAD

**Issue by arne-z** [SiLeBAT/fcl-client#933]
After a rule is created, the UI should display the following:

- [ ] Show the name of the rule
- [ ] Add a slider to switch on/off the rule --> should toggle the rule in the state
- [ ] Add an edit button --> opens the settings dialogue
- [ ] Add a delete button --> deletes the rule
- [ ] For now the list only contains one entry and items on the list should not be sortable
- [ ] The "+"-button is not present anymore. It should reappear if the rule is deleted.
